kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: ExternalName
  externalName: hdfs-service-name.hdfs-cluster.svc.cluster.local
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: spark-master
