# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  ports:
  - port: 50010
    name: fs
  clusterIP: None
  selector:
    app: hdfs-datanode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-datanode
spec:
  selector:
    matchLabels:
      app: hdfs-datanode
  serviceName: "hdfs-datanode"
  replicas: 5
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hdfs-datanode
            topologyKey: "kubernetes.io/hostname"
        
      containers:
        - name: datanode
          image: uhopper/hadoop-datanode:2.7.2
          env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://100.69.112.2:8020
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: 'false'
          ports:
          - containerPort: 50010
            name: fs
      restartPolicy: Always
