apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    app: namenode
spec:
  type: LoadBalancer
  ports:
  - port: 50070
    name: web  
  selector:
     app: namenode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: namenode
spec:
  serviceName: namenode
  replicas: 1
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: flokkr/hadoop-hdfs-namenode:latest
          resources:
            requests:
              cpu: 2000m
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /data/namenode
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: hadoopconf
---
  apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: datanode
  spec:
    serviceName: datanode
    replicas: 3
    template:
      metadata:
        labels:
          app: datanode
      spec:
        containers:
          - name: datanode
            image: flokkr/hadoop-hdfs-datanode:latest
            resources:
            requests:
              cpu: 1000m
            volumeMounts:
              - name: config
                mountPath: "/opt/hadoop/etc/hadoop"
                readOnly: true
        volumes:
          - name: config
            configMap:
              name: hadoopconf
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
     app: datanode
