# A headless service to create DNS records.
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
spec:
  ports:
  - protocol: TCP
    port: 50070
    targetPort: 50070
    name: ui
  - protocol: TCP
    port: 8020
    targetPort: 8020
    name: metadata
  selector:
    app: hdfs-namenode
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: hdfs-namenode
          image: uhopper/hadoop-namenode:2.7.2
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
            - name: HDFS_CONF_dfs_permissions
              value: 'false'
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: 'false'
            
          ports:
          - containerPort: 8020
            name: fs
      restartPolicy: Always
