apiVersion: v1
kind: Namespace
metadata:
  name: "spark-cluster"
  labels:
    name: "spark-cluster"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: clhleung/test
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            limits:
              cpu: 1300m

---

kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: LoadBalancer
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: spark-master

---

kind: Service
apiVersion: v1
metadata:
  name: spark-webui
  namespace: spark-cluster
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: spark-master

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      component: spark-worker      
  template:
    metadata:
      labels:
        component: spark-worker        
    spec:      
      containers:
        - name: spark-worker
          image: clhleung/test
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 1000m
