# This is the Kubernetes yaml file used to create the spark master 
# and worker. 

# The container images referenced could probably be changed to 
# the images created by uhopper, but you can also build your own
# images of Spark and push it to Dockerhub, from then you can reference
# in this yaml file. However, you can use my own images as long as they
# continue to exist within Dockerhub. 

apiVersion: v1
kind: Namespace
metadata:
  name: "spark-cluster"
  labels:
    name: "spark-cluster"
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: clhleung/test
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
         

---

kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
  selector:
    component: spark-master

---

kind: Service
apiVersion: v1
metadata:
  name: spark-webui
  
spec:
  type: LoadBalancer  
  ports:
    - port: 8080
      nodePort: 30048     
  selector:
    component: spark-master

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spark-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: spark-worker      
  template:
    metadata:
      labels:
        component: spark-worker        
    spec:      
      containers:
        - name: spark-worker
          image: clhleung/test
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081